# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: avalontips
site_author: realybin
site_description: Some tips for Avalonia UI

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
#    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 系统主题
plugins:
  - offline
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

  - tags:
      tags_file: tags.md

markdown_extensions:
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
copyright: 'Apache License, Version 2.0'
extra:
  status:
    new: 最近添加
    deprecated: 弃用
#  consent:
#    title: Cookie
#    description: >-
#      我们使用 Cookie 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到了他们正在搜索的内容。在您的同意下，您可以帮助我们 使我们的文档更加完善。
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/realybin/avalontips
repo_url: https://github.com/realybin/avalontips
repo_name: realybin/avalontips
edit_uri: edit/main/docs/
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js